apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-server-store
  labels:
    app: preview-server-store
    version: latest

spec:
  selector:
    matchLabels:
      app: preview-server-store
  replicas: 1
  template:
    spec:
      containers:
        # Redis
        - name: preview-server-redis
          image: redis:latest
          ports:
            - containerPort: 6379

        # MiniIO
        - name: preview-server-miniIO
          image: minio/minio
          ports:
            - containerPort: 9090
            - containerPort: 9000
          env:
            - name:  MINIO_ROOT_USER
              value: layotto
            - name: MINIO_ROOT_PASSWORD
              value: layotto_secret