apiVersion: apps/v1
kind: Deployment
metadata:
  name: preview-server-store
  namespace: layotto
  labels:
    app: preview-server-store-deployment

spec:
  selector:
    matchLabels:
      app: preview-server-store
  replicas: 1
  template:
    metadata:
      labels:
        app: preview-server-store
    spec:
      containers:
        # Redis
        - name: preview-server-redis
          image: redis:latest
          ports:
            - containerPort: 6379
        # MiniO
        - name: preview-server-minio
          image: minio/minio
          command:
            - server /data --console-address ':9090'
          ports:
            - containerPort: 9090
            - containerPort: 9000
          env:
            - name:  MINIO_ROOT_USER
              value: layotto
            - name: MINIO_ROOT_PASSWORD
              value: layotto_secret
